name: Node CI

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mocha-version: [9, 10, 11]
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: npm ci
        run: npm run ci
        env:
          CI: true
          MOCHA_VERSION: ${{ matrix.mocha-version }}
